#include "lovebird/syntax/token.hpp"

#include <format>
#include <iterator>
#include <ostream>
#include <string_view>

namespace lovebird {

std::string_view to_string(TokenKind kind) {
    switch (kind) {
        case TokenKind::end:
            return "end of input";
        case TokenKind::name:
            return "name";
        case TokenKind::keyword_break:
            return "break";
        case TokenKind::keyword_case:
            return "case";
        case TokenKind::keyword_const:
            return "const";
        case TokenKind::keyword_continue:
            return "continue";
        case TokenKind::keyword_default:
            return "default";
        case TokenKind::keyword_else:
            return "else";
        case TokenKind::keyword_embed:
            return "embed";
        case TokenKind::keyword_enum:
            return "enum";
        case TokenKind::keyword_fn:
            return "fn";
        case TokenKind::keyword_for:
            return "for";
        case TokenKind::keyword_if:
            return "if";
        case TokenKind::keyword_impl:
            return "impl";
        case TokenKind::keyword_import:
            return "import";
        case TokenKind::keyword_in:
            return "in";
        case TokenKind::keyword_let:
            return "let";
        case TokenKind::keyword_module:
            return "module";
        case TokenKind::keyword_mut:
            return "mut";
        case TokenKind::keyword_package:
            return "package";
        case TokenKind::keyword_pub:
            return "pub";
        case TokenKind::keyword_return:
            return "return";
        case TokenKind::keyword_self:
            return "self";
        case TokenKind::keyword_struct:
            return "struct";
        case TokenKind::keyword_switch:
            return "switch";
        case TokenKind::keyword_trait:
            return "trait";
        case TokenKind::keyword_type:
            return "type";
        case TokenKind::keyword_unsafe:
            return "unsafe";
        case TokenKind::paren_left:
            return "(";
        case TokenKind::paren_right:
            return ")";
        case TokenKind::bracket_left:
            return "[";
        case TokenKind::bracket_right:
            return "]";
        case TokenKind::brace_left:
            return "{";
        case TokenKind::brace_right:
            return "}";
        case TokenKind::period:
            return ".";
        case TokenKind::comma:
            return ",";
        case TokenKind::semicolon:
            return ";";
        case TokenKind::colon:
            return ":";
        case TokenKind::bang:
            return "!";
        case TokenKind::question:
            return "?";
        case TokenKind::at:
            return "@";
        case TokenKind::hash:
            return "#";
        case TokenKind::arrow:
            return "->";
        case TokenKind::plus:
            return "+";
        case TokenKind::minus:
            return "-";
        case TokenKind::star:
            return "*";
        case TokenKind::slash:
            return "/";
        case TokenKind::percent:
            return "%";
        case TokenKind::equal:
            return "=";
        case TokenKind::plus_equal:
            return "+=";
        case TokenKind::minus_equal:
            return "-=";
        case TokenKind::star_equal:
            return "*=";
        case TokenKind::slash_equal:
            return "/=";
        case TokenKind::percent_equal:
            return "%=";
        case TokenKind::tilde:
            return "~";
        case TokenKind::ampersand:
            return "&";
        case TokenKind::pipe:
            return "|";
        case TokenKind::caret:
            return "^";
        case TokenKind::less_less:
            return "<<";
        case TokenKind::greater_greater:
            return ">>";
        case TokenKind::ampersand_equal:
            return "&=";
        case TokenKind::pipe_equal:
            return "|=";
        case TokenKind::caret_equal:
            return "^=";
        case TokenKind::less_less_equal:
            return "<<=";
        case TokenKind::greater_greater_equal:
            return ">>=";
        case TokenKind::ampersand_ampersand:
            return "&&";
        case TokenKind::pipe_pipe:
            return "||";
        case TokenKind::equal_equal:
            return "==";
        case TokenKind::bang_equal:
            return "!=";
        case TokenKind::less:
            return "<";
        case TokenKind::less_equal:
            return "<=";
        case TokenKind::greater:
            return ">";
        case TokenKind::greater_equal:
            return ">=";
    }
}

std::ostream& operator<<(std::ostream& out, const Token& tok) {
    std::format_to(std::ostreambuf_iterator<char>(out), "{}", tok);
    return out;
}

}  // namespace lovebird
